import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

// All configuration lives in config.json (gitignored, generated by
// config-gen.sh). There are deliberately no environment variables and no .env.

export interface LlmConfig {
  provider: string;
  baseUrl: string;
  model: string;
  apiKey?: string;
}

export type EnergyUnit = "kcal" | "kJ";
export type MeasurementSystem = "metric" | "imperial";

/** Starting points for a new user; the Settings UI overrides them per account. */
export interface Defaults {
  targetKcal: number;
  energyUnit: EnergyUnit;
  measurementSystem: MeasurementSystem;
}

export interface Config {
  llm: LlmConfig;
  server: { port: number };
  defaults: Defaults;
}

const CONFIG_PATH = resolve(process.cwd(), "config.json");

// The default endpoint is local on purpose — see isLocalEndpoint.
const DEFAULTS: Config = {
  llm: { provider: "vLLM", baseUrl: "http://localhost:8000/v1", model: "default" },
  server: { port: 4100 },
  defaults: { targetKcal: 2000, energyUnit: "kcal", measurementSystem: "metric" },
};

const ENERGY_UNITS: EnergyUnit[] = ["kcal", "kJ"];
const MEASUREMENT_SYSTEMS: MeasurementSystem[] = ["metric", "imperial"];

function obj(v: unknown): Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v) ? (v as Record<string, unknown>) : {};
}

function str(v: unknown, fallback: string): string {
  return typeof v === "string" && v.trim() !== "" ? v : fallback;
}

function int(v: unknown, fallback: number, min: number, max: number): number {
  return typeof v === "number" && Number.isFinite(v) && v >= min && v <= max ? Math.round(v) : fallback;
}

function oneOf<T extends string>(v: unknown, allowed: T[], fallback: T): T {
  return allowed.includes(v as T) ? (v as T) : fallback;
}

/** Fill and sanity-check every key, so a hand-edited config can't crash boot. */
export function withDefaults(raw: unknown): Config {
  const root = obj(raw);
  const llm = obj(root.llm);
  const server = obj(root.server);
  const defaults = obj(root.defaults);

  const config: Config = {
    llm: {
      provider: str(llm.provider, DEFAULTS.llm.provider),
      baseUrl: str(llm.baseUrl, DEFAULTS.llm.baseUrl),
      model: str(llm.model, DEFAULTS.llm.model),
    },
    server: { port: int(server.port, DEFAULTS.server.port, 1, 65_535) },
    defaults: {
      targetKcal: int(defaults.targetKcal, DEFAULTS.defaults.targetKcal, 1, 100_000),
      energyUnit: oneOf(defaults.energyUnit, ENERGY_UNITS, DEFAULTS.defaults.energyUnit),
      measurementSystem: oneOf(defaults.measurementSystem, MEASUREMENT_SYSTEMS, DEFAULTS.defaults.measurementSystem),
    },
  };
  // Absent, not empty: an empty key would be sent as an Authorization header.
  const apiKey = str(llm.apiKey, "");
  if (apiKey) config.llm.apiKey = apiKey;
  return config;
}

export function loadConfig(path: string = CONFIG_PATH): Config {
  if (!existsSync(path)) {
    throw new Error(`config.json not found at ${path}.\nRun ./config-gen.sh to generate it.`);
  }
  try {
    return withDefaults(JSON.parse(readFileSync(path, "utf8")));
  } catch (err) {
    throw new Error(`Failed to parse config.json at ${path}: ${(err as Error).message}`);
  }
}

/**
 * True for a loopback model endpoint. Not a security boundary — it decides
 * whether to warn at startup that the user's food log (health data) is being
 * sent to a third party.
 */
export function isLocalEndpoint(baseUrl: string): boolean {
  try {
    const { hostname } = new URL(baseUrl);
    return hostname === "localhost" || hostname === "::1" || hostname === "[::1]" || /^127\./.test(hostname);
  } catch {
    return false;
  }
}
